import os
import json
import streamlit as st
import pandas as pd
import numpy as np

from src.preprocessing import TextPreprocessor
from src.train_pipeline import ModelTrainer


# Page Configuration
st.set_page_config(
    page_title="AI Fake News Detector | Classical ML & NLP",
    page_icon="📰",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom Styling
st.markdown("""
<style>
    .main-header {
        font-size: 40px;
        font-weight: 800;
        color: #1E3A8A;
        text-align: center;
        margin-bottom: 5px;
    }
    .sub-header {
        font-size: 18px;
        color: #475569;
        text-align: center;
        margin-bottom: 30px;
    }
    .verdict-box {
        padding: 24px;
        border-radius: 12px;
        text-align: center;
        margin-top: 15px;
        margin-bottom: 20px;
    }
    .verdict-real {
        background-color: #D1FAE5;
        color: #065F46;
        border: 2px solid #10B981;
    }
    .verdict-fake {
        background-color: #FEE2E2;
        color: #991B1B;
        border: 2px solid #EF4444;
    }
</style>
""", unsafe_allow_html=True)


@st.cache_resource
def get_preprocessor():
    # Explicitly use Porter stemming across entire pipeline
    return TextPreprocessor(use_stemming=True)


@st.cache_resource
def load_models_cached():
    """
    Loads trained TF-IDF vectorizer and ML models.
    Returns (None, None) if artifacts do not exist.
    """
    try:
        if os.path.exists("models/tfidf_vectorizer.joblib"):
            vectorizer, models = ModelTrainer.load_artifacts("models")
            return vectorizer, models
        return None, None
    except Exception as e:
        st.error(f"Error loading model files: {e}")
        return None, None


def load_saved_metrics():
    """
    Loads metrics.json generated by train.py.
    Returns None if missing.
    """
    metrics_path = "models/metrics.json"
    if os.path.exists(metrics_path):
        try:
            with open(metrics_path, "r") as f:
                return json.load(f)
        except Exception:
            return None
    return None


preprocessor = get_preprocessor()
vectorizer, loaded_models = load_models_cached()

# App Header
st.markdown('<div class="main-header">AI Fake News Detector</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-header">Classical Machine Learning & NLP Full-Article Classification</div>', unsafe_allow_html=True)

# Sidebar Configuration
st.sidebar.title("⚙️ Model Settings")
classifier_choice = st.sidebar.selectbox(
    "Choose Classifier Model:",
    ["Linear SVM", "Logistic Regression", "Naive Bayes", "Ensemble Majority Vote"]
)

st.sidebar.markdown("---")
st.sidebar.markdown("### 📌 Architecture Summary")
st.sidebar.info("""
**Pipeline Steps:**
1. **Full Article Input**
2. **NLTK Preprocessing** (Lowercasing, Regex Cleaning, Stopwords Removal, Porter Stemming)
3. **TF-IDF Vectorization** (Unigrams & Bigrams)
4. **Classical ML Classification** (Naive Bayes, Logistic Regression, Linear SVM)
""")

# Tabs Layout
tab_predict, tab_compare, tab_about = st.tabs(["📝 Full Article Classification", "📊 Model Benchmarks", "ℹ️ About & Methodology"])

with tab_predict:
    st.markdown("### Input News Article Text")
    st.caption("⚠️ Note: This system classifies text based solely on statistical and linguistic patterns learned during training. It does not perform external fact-checking or web verification.")

    sample_fake = "BREAKING: Secret Alien Technology Discovered in Abandoned Warehouse! Government refuses to acknowledge shocking claim."
    sample_real = "Federal Reserve Announces Interest Rate Decision Following Quarterly Economic Review and Policy Meeting."

    col_btn1, col_btn2, _ = st.columns([1, 1, 3])
    if col_btn1.button("📋 Load Sample Real News"):
        st.session_state["article_input"] = sample_real
    if col_btn2.button("⚠️ Load Sample Fake News"):
        st.session_state["article_input"] = sample_fake

    input_text = st.text_area(
        "Paste the complete body of the news article below:",
        value=st.session_state.get("article_input", ""),
        height=220,
        placeholder="Paste full news article text here..."
    )

    if st.button("🔍 Analyze Article Authenticity", type="primary", use_container_width=True):
        if not input_text.strip():
            st.error("Please enter or paste news article text to analyze.")
        elif loaded_models is None or vectorizer is None:
            st.error("Trained model artifacts are not available. Please run python train.py first.")
        else:
            cleaned_text = preprocessor.clean_text(input_text)

            if not cleaned_text.strip():
                st.warning("Processed text is empty after cleaning. Please provide valid text content.")
            else:
                st.markdown("#### 1. Preprocessing Output Preview")
                with st.expander("View Cleaned & Stemmed Tokens", expanded=False):
                    st.code(cleaned_text, language="text")

                # Transform input using pre-fitted TF-IDF vectorizer
                vec_text = vectorizer.transform([cleaned_text])

                if classifier_choice == "Ensemble Majority Vote":
                    votes = []
                    probabilities = []
                    for name, mdl in loaded_models.items():
                        pred = mdl.predict(vec_text)[0]
                        votes.append(pred)
                        if hasattr(mdl, "predict_proba"):
                            try:
                                probabilities.append(mdl.predict_proba(vec_text)[0][pred])
                            except (AttributeError, NotImplementedError):
                                pass

                    final_pred = 1 if sum(votes) >= 2 else 0
                    prob_label = "Average Model Probability"
                    confidence_str = f"{round(float(np.mean(probabilities)) * 100, 2)}%" if probabilities else "Probability not available for this classifier"
                else:
                    active_model = loaded_models.get(classifier_choice, list(loaded_models.values())[0])
                    final_pred = active_model.predict(vec_text)[0]
                    prob_label = "Model Probability"
                    
                    if hasattr(active_model, "predict_proba"):
                        try:
                            probs = active_model.predict_proba(vec_text)[0]
                            confidence_str = f"{round(float(probs[final_pred]) * 100, 2)}%"
                        except (AttributeError, NotImplementedError):
                            confidence_str = "Probability not available for this classifier"
                    else:
                        confidence_str = "Probability not available for this classifier"

                # Display Classification Result
                if final_pred == 1:
                    st.markdown(f"""
                    <div class="verdict-box verdict-real">
                        <h2 style="margin:0;">✅ REAL NEWS ARTICLE</h2>
                        <p style="font-size: 18px; font-weight: 600; margin-top:8px;">{prob_label}: {confidence_str}</p>
                        <p style="margin-bottom:0;">Classifier: {classifier_choice}</p>
                    </div>
                    """, unsafe_allow_html=True)
                else:
                    st.markdown(f"""
                    <div class="verdict-box verdict-fake">
                        <h2 style="margin:0;">⚠️ FAKE NEWS DETECTED</h2>
                        <p style="font-size: 18px; font-weight: 600; margin-top:8px;">{prob_label}: {confidence_str}</p>
                        <p style="margin-bottom:0;">Classifier: {classifier_choice}</p>
                    </div>
                    """, unsafe_allow_html=True)

                # Feature Term Importance using fitted TF-IDF matrix
                st.markdown("#### 2. Highest-Scoring Article TF-IDF Features")
                feature_names = vectorizer.get_feature_names_out()
                non_zero_indices = vec_text.nonzero()[1]

                if len(non_zero_indices) > 0:
                    tfidf_scores = [(feature_names[idx], vec_text[0, idx]) for idx in non_zero_indices]
                    tfidf_scores.sort(key=lambda x: x[1], reverse=True)
                    top_terms = tfidf_scores[:10]

                    df_features = pd.DataFrame(top_terms, columns=["TF-IDF Term", "Feature Weight Score"])
                    st.dataframe(df_features, use_container_width=True, hide_index=True)
                else:
                    st.info("No matching vocabulary terms found in vectorizer for this text.")

with tab_compare:
    st.markdown("### 📊 Model Performance from Current Training Run")
    saved_metrics = load_saved_metrics()

    if saved_metrics is not None:
        records = []
        for name, metrics in saved_metrics.items():
            records.append({
                "Model": name,
                "Accuracy": f"{metrics['Accuracy'] * 100:.2f}%" if isinstance(metrics['Accuracy'], float) else metrics['Accuracy'],
                "Precision": metrics["Precision"],
                "Recall": metrics["Recall"],
                "F1-Score": metrics["F1-Score"]
            })
        df_metrics = pd.DataFrame(records)
        st.dataframe(df_metrics, use_container_width=True, hide_index=True)

        st.markdown("#### Confusion Matrix Overview")
        cols = st.columns(len(saved_metrics))
        for idx, (name, metrics) in enumerate(saved_metrics.items()):
            with cols[idx]:
                st.markdown(f"**{name}**")
                cm = metrics.get("Confusion Matrix", [])
                if len(cm) == 2:
                    st.code(f"TN: {cm[0][0]} | FP: {cm[0][1]}\nFN: {cm[1][0]} | TP: {cm[1][1]}", language="text")
                else:
                    st.write(cm)
    else:
        st.warning("Model evaluation metrics are not available. Run python train.py to generate them.")

with tab_about:
    st.markdown("### ℹ️ Project Architecture & Methodology")
    st.markdown("""
    This project provides a clean, explainable **Classical Machine Learning + Natural Language Processing** system to classify full news articles as **Fake** or **Real**.

    #### Pipeline Components:
    1. **Full Article Input**: Accepts complete text body of news articles.
    2. **NLP Preprocessing (`src/preprocessing.py`)**:
       - Lowercasing transformation
       - URL and HTML tag stripping
       - Special character and punctuation removal
       - NLTK English stopword filtering
       - NLTK Porter Stemming (`TextPreprocessor(use_stemming=True)`)
    3. **Feature Vectorization**:
       - `TfidfVectorizer` (Term Frequency-Inverse Document Frequency)
       - Sublinear TF scaling with unigram and bigram n-grams
    4. **Classical ML Classifiers**:
       - **Multinomial Naive Bayes**
       - **Logistic Regression**
       - **Linear SVM** (`LinearSVC` / `CalibratedClassifierCV`)
    5. **No Deep Learning / No LLM**: Completely lightweight, fast, reproducible, and verifiable.
    """)

st.markdown("---")
st.caption("AI Fake News Detection System • Classical ML + NLP Architecture • Powered by Scikit-Learn, NLTK & Streamlit")
