import React from 'react';
import { ShieldAlert } from 'lucide-react';

export default function AdvisoryNotice({ compact = false }) {
  return (
    <div className={`rounded-xl bg-amber-950/40 border border-amber-500/30 text-amber-200/90 ${
      compact ? 'p-3 text-xs' : 'p-4 text-sm'
    } flex items-start gap-3 shadow-inner`}>
      <ShieldAlert className={`${compact ? 'w-4 h-4' : 'w-5 h-5'} text-amber-400 shrink-0 mt-0.5`} />
      <div className="space-y-0.5">
        <p className="font-semibold text-amber-300 font-mono tracking-wide text-xs uppercase">
          AI Decision Support — Advisory Only
        </p>
        <p className="text-xs text-amber-200/80 leading-relaxed">
          All recommendations (Reorder, Expedite, Transfer, Escalate) are analytical decision-support outputs generated by deterministic services and LLMs. The platform does not execute purchase orders or inventory mutations automatically.
        </p>
      </div>
    </div>
  );
}
