from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
from enum import Enum

from app.llm.schemas import IntentEnum, ExtractedEntities, Source, AffectedProduct, RecommendedAction


class ToolEnum(str, Enum):
    SQL = "SQL"
    RAG = "RAG"
    FORECAST = "FORECAST"
    RISK = "RISK"
    SIMULATION = "SIMULATION"


class PlannerOutput(BaseModel):
    """
    Structured response generated by the Planner Agent Node.
    """
    intent: IntentEnum = Field(..., description="Target intent category")
    entities: ExtractedEntities = Field(default_factory=ExtractedEntities, description="Extracted domain parameters")
    tools: List[ToolEnum] = Field(default_factory=list, description="Ordered list of required tools to execute")
    reason: str = Field("", description="Justification for tool selection and workflow plan")


class AgentQueryRequest(BaseModel):
    """
    User query request for the LangGraph Agent endpoint.
    """
    question: str = Field(..., min_length=1, description="Natural language supply chain question")
    supplier_filter: Optional[str] = Field(None, description="Optional supplier filter")
    top_k: int = Field(5, ge=1, le=20, description="Max RAG chunks to retrieve if RAG tool is used")
    provider_override: Optional[str] = Field(None, description="Override LLM provider (fake, ollama, openai)")


class StepTraceItem(BaseModel):
    """
    Metadata describing an individual execution step within the LangGraph workflow.
    Exposed for execution auditing and frontend debugging.
    """
    step: str = Field(..., description="Name of graph node/step")
    status: str = Field(..., description="Step status (started, completed, failed, skipped)")
    timestamp: Optional[str] = Field(None, description="ISO timestamp of step execution")
    detail: Optional[str] = Field(None, description="High-level summary of step action or results")


class AgentQueryResponse(BaseModel):
    """
    Comprehensive structured response returned by the LangGraph Multi-Tool Agent Orchestrator.
    Compatible with Phase 6 CopilotResponse while providing full step trace provenance.
    """
    question: str = Field(..., description="Original user question")
    summary: str = Field(..., description="Executive summary of answer")
    intent: str = Field(..., description="Identified intent category")
    answer: str = Field(..., description="Comprehensive grounded natural-language answer")
    risk_level: Optional[str] = Field(None, description="Overall inventory risk level (LOW, MEDIUM, HIGH, CRITICAL)")
    affected_products: List[AffectedProduct] = Field(default_factory=list, description="Products impacted or mentioned")
    recommended_actions: List[RecommendedAction] = Field(default_factory=list, description="Actionable recommendations")
    explanation: str = Field(..., description="Detailed analytical synthesis")
    confidence: float = Field(..., description="Overall confidence score (0.0 to 1.0)")
    sources: List[Source] = Field(default_factory=list, description="Retrieved evidence document citations")
    data_used: List[str] = Field(default_factory=list, description="Tools and data services executed")
    warnings: List[str] = Field(default_factory=list, description="Boundary notices or tool failure warnings")
    tool_trace: List[Dict[str, Any]] = Field(default_factory=list, description="Safe high-level execution step log")
